<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <PublishAot>true</PublishAot>
    <StripSymbols>false</StripSymbols>
    <OptimizationPreference>Size</OptimizationPreference>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RuntimeFrameworkVersion>8.0.22</RuntimeFrameworkVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <LinkerArg Include="/MAP:$(NativeAotMapPath)" Condition="'$(OS)' == 'Windows_NT' and '$(NativeAotMapPath)' != ''" />
  </ItemGroup>
</Project>
